// Minimal, ASCII-only app.js with safe runPredictions ordering
const API_BASE='https://www.thebluealliance.com/api/v3';
const DEFAULT_HOME_TEAM='frc245';
let state={tbaKey:'',eventKey:'',year:(new Date()).getFullYear(),teams:[],matches:[],rankings:null,oprs:null,teamMap:new Map(),elo:new Map(),stats:new Map(),predictions:[],kFactor:24,blend:0.5,homeTeam:DEFAULT_HOME_TEAM,rebuiltData:[]};
// state.rebuiltData = [{"Team": "6002", "Alliance": "Blue", "Alliances Blue Score": 331, "Alliances Red Score": 466, "Winning Alliance": "red"}]; // Placeholder: replace with full JSON from Excel
const $=(s)=>document.querySelector(s); const $$=(s)=>Array.from(document.querySelectorAll(s));
const fmtTeam=(k)=>k.replace('frc','');
const toLocal=(secs)=>secs? new Date(secs*1000).toLocaleString() : '-';
const sum=(a)=>a.reduce((x,y)=>x+y,0); const mean=(a)=>a.length? sum(a)/a.length:0; const stdev=(a)=>{const m=mean(a); return Math.sqrt(mean(a.map(x=>(x-m)*(x-m))));};
const clamp=(x,lo,hi)=>Math.max(lo,Math.min(hi,x)); const logistic=(x)=>1/(1+Math.pow(Math.E,-x));
function runPredictions(){} // stub, replaced later
function saveLocal(){const c={tbaKey:state.tbaKey,lastEvent:state.eventKey,lastYear:state.year,homeTeam:state.homeTeam}; localStorage.setItem('frc_cfg',JSON.stringify(c));}
function loadLocal(){try{const c=JSON.parse(localStorage.getItem('frc_cfg')||'{}'); if(c.tbaKey)state.tbaKey=c.tbaKey; if(c.lastEvent)state.eventKey=c.lastEvent; if(c.lastYear)state.year=c.lastYear; if(c.homeTeam)state.homeTeam=c.homeTeam; $('#tbaKey').value=state.tbaKey||''; $('#eventKey').value=state.eventKey||''; $('#seasonYear').value=state.year||''; $('#homeTeam').value=fmtTeam(state.homeTeam); $('#coachTeam').textContent=fmtTeam(state.homeTeam);}catch(e){}}
async function api(p){ if(!state.tbaKey) throw new Error('Missing TBA key'); const r=await fetch(API_BASE+p,{headers:{'X-TBA-Auth-Key':state.tbaKey}}); if(!r.ok){throw new Error('TBA '+r.status+': '+(await r.text()));} return r.json(); }
const cacheKey=(p)=>'cache:'+p; async function apiCached(p,useCache=true){const k=cacheKey(p); if(useCache){const h=localStorage.getItem(k); if(h) return JSON.parse(h);} const d=await api(p); try{localStorage.setItem(k,JSON.stringify(d));}catch(e){} return d; }
function clearCache(){Object.keys(localStorage).forEach(k=>{if(k.startsWith('cache:')) localStorage.removeItem(k);});}
async function loadEventData(){ try{ const useCache=($('#useCache').value==='true'); state.eventKey=$('#eventKey').value.trim(); state.year=parseInt($('#seasonYear').value||String((new Date()).getFullYear()),10); state.kFactor=parseFloat($('#eloK').value||'24'); if(!state.eventKey){alert('Please enter an event key (e.g., 2026milak)'); return;} if(!state.tbaKey){alert('Please paste your TBA API key.'); return;} const [teams,matches,rankings,oprs]=await Promise.all([
  apiCached('/event/'+state.eventKey+'/teams/simple',useCache),
  apiCached('/event/'+state.eventKey+'/matches',useCache),
  apiCached('/event/'+state.eventKey+'/rankings',useCache).catch(_=>null),
  apiCached('/event/'+state.eventKey+'/oprs',useCache).catch(_=>null)]);
  state.teams=teams; state.matches=matches.sort((a,b)=> (a.time||a.predicted_time||0)-(b.time||b.predicted_time||0)); state.rankings=rankings; state.oprs=oprs; state.teamMap=new Map(teams.map(t=>[t.key,t]));
  // Fetch score breakdowns for played matches
  const playedMatches = state.matches.filter(m => m.alliances && m.alliances.red && m.alliances.red.score != null && m.alliances.red.score >= 0);
  console.log('Number of played matches: ' + playedMatches.length);
  console.log('API key set: ' + !!state.tbaKey);
  const breakdownPromises = playedMatches.map((m, idx) => apiCached('/match/' + m.key, useCache).then(d => { 
    console.log('Match API response for ' + m.key + ', keys:', Object.keys(d || {}));
    if (d && d.score_breakdown) {
      m.score_breakdown = d.score_breakdown;
      console.log('✓ Attached breakdown for ' + m.key + ' (red keys: ' + Object.keys(d.score_breakdown.red || {}).length + ')');
    } else {
      console.warn('✗ No score_breakdown in response for ' + m.key);
      console.log('Full response:', d);
    }
  }).catch(e => { console.error('Failed to fetch breakdown for ' + m.key, e); }));
  await Promise.all(breakdownPromises).catch(e => console.error('Breakdown fetch errors:', e));
  const matchesWithBreakdown = state.matches.filter(m => m.score_breakdown).length;
  console.log('Matches with breakdowns: ' + matchesWithBreakdown + ' out of ' + state.matches.length);  if (matchesWithBreakdown > 0) {
    const firstWithBreak = state.matches.find(m => m.score_breakdown);
    console.log('First match with breakdown (' + firstWithBreak.key + '), red breakdown type:', typeof firstWithBreak.score_breakdown.red, 'has totalAutoPoints:', !!firstWithBreak.score_breakdown.red.totalAutoPoints);
  }  computeTeamStats(); computeElo(); runPredictions(); populateStrategyMatchSelector(); renderAll();
} catch(e){ console.error(e); alert('Error loading data: '+e.message);} }
function computeTeamStats(){ state.stats=new Map(); for(const t of state.teams){ state.stats.set(t.key,{team:t,played:0,wins:0,losses:0,ties:0,pts:[],avg:0,stdev:0,maxAuton:0,maxTeleop:0,maxEndgame:0}); } for(const m of state.matches){ const red=(m.alliances&&m.alliances.red? m.alliances.red.team_keys:[])||[]; const blue=(m.alliances&&m.alliances.blue? m.alliances.blue.team_keys:[])||[]; const rs=m.alliances&&m.alliances.red? m.alliances.red.score:null; const bs=m.alliances&&m.alliances.blue? m.alliances.blue.score:null; if(rs!=null&&bs!=null&&rs>=0&&bs>=0){ for(const tk of red){ const st=state.stats.get(tk); if(st){ st.played++; st.pts.push(rs);} } for(const tk of blue){ const st=state.stats.get(tk); if(st){ st.played++; st.pts.push(bs);} } if(rs>bs){ for(const tk of red){ const st=state.stats.get(tk); if(st) st.wins++; } for(const tk of blue){ const st=state.stats.get(tk); if(st) st.losses++; } } else if(bs>rs){ for(const tk of blue){ const st=state.stats.get(tk); if(st) st.wins++; } for(const tk of red){ const st=state.stats.get(tk); if(st) st.losses++; } } else { for(const tk of red.concat(blue)){ const st=state.stats.get(tk); if(st) st.ties++; } } } } for(const [k,st] of state.stats){ st.avg=mean(st.pts); st.stdev=stdev(st.pts);} 
  // Compute max scores from breakdowns
  let breakdownsProcessed = 0;
  let teamsUpdated = 0;
  for(const m of state.matches){ if(!m.score_breakdown) continue; breakdownsProcessed++; const redBreak=m.score_breakdown.red; const blueBreak=m.score_breakdown.blue; const redTeams=(m.alliances&&m.alliances.red? m.alliances.red.team_keys:[])||[]; const blueTeams=(m.alliances&&m.alliances.blue? m.alliances.blue.team_keys:[])||[]; for(const tk of redTeams){ const st=state.stats.get(tk); if(st){ teamsUpdated++; const autoVal = redBreak.totalAutoPoints || redBreak.autoPoints || redBreak.auto || 0; const telVal = redBreak.totalTeleopPoints || redBreak.teleopPoints || redBreak.teleop || 0; const endVal = redBreak.endGameTowerPoints || redBreak.endgamePoints || redBreak.endgame || 0; st.maxAuton=Math.max(st.maxAuton, autoVal); st.maxTeleop=Math.max(st.maxTeleop, telVal); st.maxEndgame=Math.max(st.maxEndgame, endVal); } } for(const tk of blueTeams){ const st=state.stats.get(tk); if(st){ teamsUpdated++; const autoVal = blueBreak.totalAutoPoints || blueBreak.autoPoints || blueBreak.auto || 0; const telVal = blueBreak.totalTeleopPoints || blueBreak.teleopPoints || blueBreak.teleop || 0; const endVal = blueBreak.endGameTowerPoints || blueBreak.endgamePoints || blueBreak.endgame || 0; st.maxAuton=Math.max(st.maxAuton, autoVal); st.maxTeleop=Math.max(st.maxTeleop, telVal); st.maxEndgame=Math.max(st.maxEndgame, endVal); } } }
  console.log('Breakdown processing complete: ' + breakdownsProcessed + ' breakdowns, ' + teamsUpdated + ' team updates'); }
function computeElo(){ state.elo=new Map(state.teams.map(t=>[t.key,1500])); const K=state.kFactor||24; for(const m of state.matches){ const red=(m.alliances&&m.alliances.red? m.alliances.red.team_keys:[])||[]; const blue=(m.alliances&&m.alliances.blue? m.alliances.blue.team_keys:[])||[]; const rs=m.alliances&&m.alliances.red? m.alliances.red.score:null; const bs=m.alliances&&m.alliances.blue? m.alliances.blue.score:null; if(rs==null||bs==null||rs<0||bs<0) continue; const redE=sum(red.map(tk=> state.elo.get(tk)||1500)); const blueE=sum(blue.map(tk=> state.elo.get(tk)||1500)); const qR=Math.pow(10, redE/4000); const qB=Math.pow(10, blueE/4000); const expR=qR/(qR+qB); const expB=1-expR; let sR=0.5,sB=0.5; if(rs>bs){sR=1;sB=0;} else if(bs>rs){sR=0;sB=1;} const dR=K*(sR-expR); const dB=K*(sB-expB); for(const tk of red){ state.elo.set(tk,(state.elo.get(tk)||1500)+dR/Math.max(1,red.length)); } for(const tk of blue){ state.elo.set(tk,(state.elo.get(tk)||1500)+dB/Math.max(1,blue.length)); } } }
function predictWithOPR(match){ if(!state.oprs) return null; const red=(match.alliances&&match.alliances.red? match.alliances.red.team_keys:[])||[]; const blue=(match.alliances&&match.alliances.blue? match.alliances.blue.team_keys:[])||[]; const redSum=sum(red.map(tk=> state.oprs.oprs[tk]||0)); const blueSum=sum(blue.map(tk=> state.oprs.oprs[tk]||0)); const diff=redSum-blueSum; const scale=state._oprAllianceStdev||15; const pR=logistic(diff/scale); return {expRed:redSum,expBlue:blueSum,pRed:pR,pBlue:1-pR,model:'OPR'}; }
function predictWithElo(match){ const red=(match.alliances&&match.alliances.red? match.alliances.red.team_keys:[])||[]; const blue=(match.alliances&&match.alliances.blue? match.alliances.blue.team_keys:[])||[]; const redE=sum(red.map(tk=> state.elo.get(tk)||1500)); const blueE=sum(blue.map(tk=> state.elo.get(tk)||1500)); const qR=Math.pow(10, redE/4000); const qB=Math.pow(10, blueE/4000); const pR=qR/(qR+qB); const base=(mean(red.map(tk=> (state.stats.get(tk)? state.stats.get(tk).avg:0)))+mean(blue.map(tk=> (state.stats.get(tk)? state.stats.get(tk).avg:0))))/2; const expDiff=(pR-(1-pR))*10; return {expRed:Math.max(0,base+expDiff/2), expBlue:Math.max(0,base-expDiff/2), pRed:pR, pBlue:1-pR, model:'Elo'}; }
// scouting
state.scouting={rows:[],byMatch:new Map(),byTeam:new Map()}; state.scoutWeight=0.20;
function parseCSV(text){const rows=[]; let i=0,field='',inQuotes=false,row=[]; while(i<text.length){const c=text[i]; if(inQuotes){ if(c==='"'){ if(text[i+1]==='"'){field+='"'; i++;} else {inQuotes=false;} } else {field+=c;} } else { if(c==='"'){inQuotes=true;} else if(c===','){row.push(field); field='';} else if(c==='\n'||c==='\r'){ if(field!==''||row.length){row.push(field); rows.push(row); row=[]; field='';} } else {field+=c;} } i++; } if(field!==''||row.length){row.push(field); rows.push(row);} const header=(rows.shift()||[]).map(h=>h.trim()); return rows.filter(r=>r.length&&r.some(x=>x!=='')).map(r=>{const o={}; for(let j=0;j<header.length;j++){o[header[j]]=(r[j]!==undefined?r[j]:'');} return o;});}
function toNum(v){ if(v===undefined||v===null||v==='') return null; const x=Number(v); return isNaN(x)? null:x; }
function to01(v){ if(v===undefined||v===null||v==='') return null; const s=String(v).trim().toLowerCase(); return (s==='1'||s==='true')?1:0; }
function ingestScouting(rows){ const ek=state.eventKey; const filtered=rows.filter(r=> !ek || String((r.event_key||r.eventKey||'')).trim()===ek); const byTeam=new Map(); const byMatch=new Map(); for(const r of filtered){ const team=String((r.team_key||r.team||'')).trim(); if(!team) continue; const mkey=String((r.match_key||r.matchKey||'')).trim(); if(mkey){ if(!byMatch.has(mkey)) byMatch.set(mkey,[]); byMatch.get(mkey).push(r);} if(!byTeam.has(team)) byTeam.set(team,{n:0,contrib:[],tele:[],endg:[],fuel:[],climb:[],drv:[],score:[],defense:[],notes:[],auto:[],climbPoints:[]}); const t=byTeam.get(team); t.n++; const push=(arr,v)=>{const x=toNum(v); if(x!==null) arr.push(x);} ; push(t.contrib,r.contributedPoints); push(t.tele,r.TeleopPoints||r.teleop||r.teleopPoints); push(t.endg,r.EndgamePoints||r.endgame||r.endgamePoints); push(t.fuel,r.FuelPoints||r.fuel||r.fuelPoints); const dc=to01(r.DidClimb); if(dc!==null) t.climb.push(dc); push(t.drv,r.qDriverSkill); push(t.score,r.qScoringSkill); push(t.defense,r.qDefenseQuality); push(t.auto,r.AutoPoints); push(t.climbPoints,r.ClimbPoints); const note=[r.otherNotes,r.superNotes].filter(Boolean).join(' | '); if(note) t.notes.push(note);} state.scouting.rows=filtered; state.scouting.byTeam=byTeam; state.scouting.byMatch=byMatch; try{const comp=Array.from(byTeam.entries()).map(([k,v])=>({k,n:v.n,c:mean(v.contrib),t:mean(v.tele),e:mean(v.endg),f:mean(v.fuel),climb:mean(v.climb),drv:mean(v.drv),scr:mean(v.score),d:mean(v.defense),notes:v.notes.slice(-4),auto:mean(v.auto),climbPoints:mean(v.climbPoints)})); localStorage.setItem('frc_scout_summary',JSON.stringify({event:state.eventKey,data:comp}));}catch(e){} renderScouting(); runPredictions(); renderCoachView(); buildCSV(); }
function loadScoutingFromLocal(){ try{ const raw=JSON.parse(localStorage.getItem('frc_scout_summary')||'null'); if(raw&&raw.event===state.eventKey){ const byTeam=new Map(); for(const r of raw.data){ byTeam.set(r.k,{n:r.n,contrib:[r.c],tele:[r.t],endg:[r.e],fuel:[r.f],climb:[r.climb],drv:[r.drv],score:[r.scr],defense:[r.d],notes:r.notes||[],auto:[r.auto],climbPoints:[r.climbPoints]}); } state.scouting.byTeam=byTeam; state.scouting.rows=[]; state.scouting.byMatch=new Map(); } }catch(e){} }
const teamSOR=(k)=>{const t=state.scouting.byTeam.get(k); return t? mean(t.contrib):null;};
function adjustedOPRValue(tk){ const opr=state.oprs&&state.oprs.oprs? state.oprs.oprs[tk]:null; const sor=teamSOR(tk); const w=state.scoutWeight||0; if(opr==null&&sor==null) return 0; if(opr==null) return sor; if(sor==null) return opr; return (1-w)*opr + w*sor; }
function predictWithOPRAdjusted(m){ if(!state.oprs && state.scouting.byTeam.size===0) return null; const red=(m.alliances&&m.alliances.red? m.alliances.red.team_keys:[])||[]; const blue=(m.alliances&&m.alliances.blue? m.alliances.blue.team_keys:[])||[]; const redSum=red.map(adjustedOPRValue).reduce((a,b)=>a+(b||0),0); const blueSum=blue.map(adjustedOPRValue).reduce((a,b)=>a+(b||0),0); const diff=redSum-blueSum; const scale=state._oprAllianceStdev||15; const pR=logistic(diff/scale); return {expRed:redSum,expBlue:blueSum,pRed:pR,pBlue:1-pR,model:(state.scoutWeight>0? 'OPR+Scout('+state.scoutWeight.toFixed(2)+')':'OPR')}; }
runPredictions=function(){ if(state.oprs){ const sums=[]; for(const m of state.matches){ const red=(m.alliances&&m.alliances.red? m.alliances.red.team_keys:[])||[]; const blue=(m.alliances&&m.alliances.blue? m.alliances.blue.team_keys:[])||[]; sums.push(sum(red.map(tk=> (state.oprs.oprs[tk]||0)))); sums.push(sum(blue.map(tk=> (state.oprs.oprs[tk]||0)))); } state._oprAllianceStdev=stdev(sums.filter(x=>isFinite(x))); } state.predictions=[]; const blend=state.blend; for(const m of state.matches){ const rs=m.alliances&&m.alliances.red? m.alliances.red.score:null; const bs=m.alliances&&m.alliances.blue? m.alliances.blue.score:null; if(rs!=null&&bs!=null&&rs>=0&&bs>=0) continue; const pOPR=predictWithOPRAdjusted(m); const pElo=predictWithElo(m); let expRed,expBlue,pRed,pBlue,model; if(pOPR&&pElo){ expRed=(1-blend)*pOPR.expRed + blend*pElo.expRed; expBlue=(1-blend)*pOPR.expBlue + blend*pElo.expBlue; pRed=clamp((1-blend)*pOPR.pRed + blend*pElo.pRed,0,1); pBlue=1-pRed; model='Hybrid('+blend.toFixed(2)+')'; } else if(pOPR){ ({expRed,expBlue,pRed,pBlue,model}=pOPR); } else if(pElo){ ({expRed,expBlue,pRed,pBlue,model}=pElo); } state.predictions.push({match:m,expRed,expBlue,pRed,pBlue,model}); } };
// coach/strategy renderers (shortened)
function isTeamOnAlliance(tk,arr){return arr.includes(tk);} const allianceStr=(ks)=>ks.map(fmtTeam).join(', ');
function getUpcomingMatchesForTeam(tk,c=3){const up=[]; for(const m of state.matches){ const rs=m.alliances&&m.alliances.red? m.alliances.red.score:null; const bs=m.alliances&&m.alliances.blue? m.alliances.blue.score:null; if(rs!=null&&bs!=null&&rs>=0&&bs>=0) continue; const red=(m.alliances&&m.alliances.red? m.alliances.red.team_keys:[])||[]; const blue=(m.alliances&&m.alliances.blue? m.alliances.blue.team_keys:[])||[]; if(isTeamOnAlliance(tk,red)||isTeamOnAlliance(tk,blue)) up.push(m);} return up.slice(0,c);} 
function findPredictionForMatch(k){return state.predictions.find(p=>p.match.key===k);} 
function renderCoachView(){ const tk=state.homeTeam; $('#coachTeam').textContent=fmtTeam(tk); const n=parseInt($('#coachCount').value||'3',10); const up=getUpcomingMatchesForTeam(tk,n); const tbody=$('#tblCoach tbody'); tbody.innerHTML=''; for(const m of up){ const pred=findPredictionForMatch(m.key); const red=(m.alliances&&m.alliances.red? m.alliances.red.team_keys:[])||[]; const blue=(m.alliances&&m.alliances.blue? m.alliances.blue.team_keys:[])||[]; const ours=isTeamOnAlliance(tk,red)? red:blue; const opps=isTeamOnAlliance(tk,red)? blue:red; const ourWin=isTeamOnAlliance(tk,red)? (pred?pred.pRed:0.5):(pred?pred.pBlue:0.5); const plan=ourWin>=0.5? 'Run standard cycles; avoid penalties; secure endgame.' : 'Play controlled defense on their top scorer; secure endgame; minimize risk.'; const tr=document.createElement('tr'); tr.innerHTML='<td>'+m.key+'</td><td>'+toLocal(m.time||m.predicted_time)+'</td><td><span class="badge badge-gold">'+allianceStr(ours)+'</span></td><td>'+allianceStr(opps)+'</td><td>'+ (ourWin*100).toFixed(1) +'%</td><td>'+plan+'</td>'; tbody.appendChild(tr);} const ul=$('#coachNotes'); ul.innerHTML=''; }
function renderRebuiltSummary(){ const teamInput = $('#rebuiltTeam').value.trim(); if(!teamInput){ alert('Please enter a team number.'); return; } const team = 'frc' + teamInput; const teamData = state.rebuiltData.filter(d => d.Team === teamInput); if(teamData.length === 0){ $('#rebuiltSummary').innerHTML = '<p>No data found for team ' + teamInput + '.</p>'; return; } const totalMatches = teamData.length; const wins = teamData.filter(d => (d.Alliance === 'Blue' && d['Winning Alliance'] === 'blue') || (d.Alliance === 'Red' && d['Winning Alliance'] === 'red')).length; const losses = totalMatches - wins; const winRate = (wins / totalMatches * 100).toFixed(1) + '%'; const avgScore = mean(teamData.map(d => d.Alliance === 'Blue' ? d['Alliances Blue Score'] : d['Alliances Red Score'])).toFixed(1); const avgAuto = mean(teamData.map(d => d.Alliance === 'Blue' ? d['Score Breakdown Blue Totalautopoints'] : d['Score Breakdown Red Totalautopoints'])).toFixed(1); const avgTeleop = mean(teamData.map(d => d.Alliance === 'Blue' ? d['Score Breakdown Blue Totalteleoppoints'] : d['Score Breakdown Red Totalteleoppoints'])).toFixed(1); const avgEndgame = mean(teamData.map(d => d.Alliance === 'Blue' ? d['Score Breakdown Blue Endgametowerpoints'] : d['Score Breakdown Red Endgametowerpoints'])).toFixed(1); const html = '<h4>Team ' + teamInput + ' Summary</h4><ul><li>Total Matches: ' + totalMatches + '</li><li>Win Rate: ' + winRate + '</li><li>Average Score: ' + avgScore + '</li><li>Average Auto Points: ' + avgAuto + '</li><li>Average Teleop Points: ' + avgTeleop + '</li><li>Average Endgame Points: ' + avgEndgame + '</li></ul>'; $('#rebuiltSummary').innerHTML = html; }
function computeRole(teamKey){return 'Role';} function consistencyLabel(teamKey){return 'Consistency';}
function populateStrategyMatchSelector(){const sel=$('#strategyMatch'); if(!sel) return; sel.innerHTML=''; const tk=state.homeTeam; const up=getUpcomingMatchesForTeam(tk,50); for(const m of up){ const o=document.createElement('option'); o.value=m.key; o.textContent=m.key+' - '+toLocal(m.time||m.predicted_time); sel.appendChild(o);} }
function buildStrategy(){alert('Strategy built.');}
// picklist, predictions, teams, matches
function renderMetrics(){ $('#mUpdated')&&($('#mUpdated').textContent=(new Date()).toLocaleString()); }
function renderTeams(){ const tbody=$('#tblTeams tbody'); if(!tbody) return; tbody.innerHTML=''; const entries=Array.from(state.stats.entries()); entries.sort((a,b)=>(state.elo.get(b[0])||1500)-(state.elo.get(a[0])||1500)); for(const [k,st] of entries){ const team=state.teamMap.get(k); const elo=(state.elo.get(k)||1500); const opr=(state.oprs&&state.oprs.oprs? state.oprs.oprs[k]:null); const tr=document.createElement('tr'); if(k===state.homeTeam) tr.classList.add('highlight-245'); tr.innerHTML='<td><strong>'+fmtTeam(k)+'</strong></td><td>'+(team? team.nickname||'':'')+'</td><td>'+Math.round(elo)+'</td><td>'+(opr?opr.toFixed(1):'-')+'</td><td>'+st.wins+'-'+st.losses+'-'+st.ties+'</td><td>'+(st.avg?st.avg.toFixed(1):'-')+'</td><td>'+computeRole(k)+'</td><td>'+consistencyLabel(k)+'</td>'; tbody.appendChild(tr);} }
function renderMatches(){ const tbody=$('#tblMatches tbody'); if(!tbody) return; tbody.innerHTML=''; for(const m of state.matches){ const red=(m.alliances&&m.alliances.red? m.alliances.red.team_keys:[])||[]; const blue=(m.alliances&&m.alliances.blue? m.alliances.blue.team_keys:[])||[]; const rs=m.alliances&&m.alliances.red? m.alliances.red.score:null; const bs=m.alliances&&m.alliances.blue? m.alliances.blue.score:null; const winner=(rs!=null&&bs!=null&&rs>=0&&bs>=0)? (rs>bs? 'Red':(bs>rs?'Blue':'Tie')):'-'; const comp=m.comp_level? m.comp_level.toUpperCase():'QM'; const set=m.set_number||''; const matchNum=m.match_number||''; const tr=document.createElement('tr'); tr.innerHTML='<td>'+m.key+'</td><td>'+comp+'</td><td>'+set+(set?'-':'')+matchNum+'</td><td>'+red.map(fmtTeam).join(', ')+'</td><td>'+blue.map(fmtTeam).join(', ')+'</td><td>'+(rs!=null&&rs>=0?rs:'-')+'</td><td>'+(bs!=null&&bs>=0?bs:'-')+'</td><td>'+winner+'</td><td>'+toLocal(m.time||m.predicted_time)+'</td>'; tbody.appendChild(tr);} }
function renderPredictions(){ const tbody=$('#tblPredictions tbody'); if(!tbody) return; tbody.innerHTML=''; for(const p of state.predictions){ const m=p.match; const red=(m.alliances&&m.alliances.red? m.alliances.red.team_keys:[])||[]; const blue=(m.alliances&&m.alliances.blue? m.alliances.blue.team_keys:[])||[]; const tr=document.createElement('tr'); tr.innerHTML='<td>'+m.key+'</td><td>'+red.map(fmtTeam).join(', ')+'</td><td>'+blue.map(fmtTeam).join(', ')+'</td><td>'+ (p.expRed?p.expRed.toFixed(1):'-') +'</td><td>'+ (p.expBlue?p.expBlue.toFixed(1):'-') +'</td><td>'+ (p.pRed*100).toFixed(1)+'%</td><td>'+ (p.pBlue*100).toFixed(1)+'%</td><td>'+p.model+'</td>'; tbody.appendChild(tr);} }
function renderScouting(){ const tbody=document.querySelector('#tblScouting tbody'); if(!tbody) return; tbody.innerHTML=''; const rows=Array.from(state.scouting.byTeam.entries()).map(([k,v])=>({team:fmtTeam(k),key:k,n:v.n,contrib:mean(v.contrib),tele:mean(v.tele),endg:mean(v.endg),fuel:mean(v.fuel),climb:mean(v.climb),drv:mean(v.drv),score:mean(v.score),notes:(v.notes||[]).join(' | '),auto:mean(v.auto),climbPoints:mean(v.climbPoints),d:mean(v.defense)})); rows.sort((a,b)=>b.contrib-a.contrib); for(const r of rows){ const tr=document.createElement('tr'); if(r.key===state.homeTeam) tr.classList.add('highlight-245'); tr.innerHTML='<td><strong>'+r.team+'</strong></td><td>'+(r.n||0)+'</td><td>'+ (r.contrib||0).toFixed(1) +'</td><td>'+ (r.auto||0).toFixed(1) +'</td><td>'+ (r.tele||0).toFixed(1) +'</td><td>'+ (r.endg||0).toFixed(1) +'</td><td>'+ (r.fuel||0).toFixed(1) +'</td><td>'+ (isFinite(r.climb)? (r.climb*100).toFixed(0)+'%':'-') +'</td><td>'+ (isFinite(r.climbPoints)? r.climbPoints.toFixed(1):'-') +'</td><td>'+ (isFinite(r.d)? r.d.toFixed(1):'-') +'</td><td>'+ (isFinite(r.drv)? r.drv.toFixed(1):'-') +'</td><td>'+ (isFinite(r.score)? r.score.toFixed(1):'-') +'</td><td><span class="scout-note">'+(r.notes||'')+'</span></td>'; tbody.appendChild(tr);} }
function buildCSV(){ const rows=[['match_key','red_teams','blue_teams','exp_red_pts','exp_blue_pts','red_win_p','blue_win_p','model']]; for(const p of state.predictions){ const m=p.match; const red=(m.alliances&&m.alliances.red? m.alliances.red.team_keys:[])||[]; const blue=(m.alliances&&m.alliances.blue? m.alliances.blue.team_keys:[])||[]; rows.push([m.key, red.map(fmtTeam).join(' '), blue.map(fmtTeam).join(' '), p.expRed? p.expRed.toFixed(2):'', p.expBlue? p.expBlue.toFixed(2):'', (p.pRed*100).toFixed(1), (p.pBlue*100).toFixed(1), p.model]); } const csv=rows.map(r=> r.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv'}); const url=URL.createObjectURL(blob); const a=document.getElementById('btn-download-csv'); if(a) a.href=url; }
function renderAll(){ renderMetrics(); renderTeams(); renderMatches(); renderPredictions(); renderCoachView(); try{ buildCSV(); }catch(e){} }
window.addEventListener('DOMContentLoaded',()=>{ loadScoutingFromLocal(); loadLocal(); $('#blend')&&$('#blend').addEventListener('input',(e)=>{ state.blend=parseFloat(e.target.value); $('#blendLabel')&&($('#blendLabel').textContent=state.blend.toFixed(2)); }); $('#scoutWeight')&&$('#scoutWeight').addEventListener('input',(e)=>{ state.scoutWeight=parseFloat(e.target.value||'0'); $('#scoutWeightLabel')&&($('#scoutWeightLabel').textContent=state.scoutWeight.toFixed(2)); runPredictions(); renderAll(); }); $('#btn-save-key')&&$('#btn-save-key').addEventListener('click',()=>{ state.tbaKey=$('#tbaKey').value.trim(); saveLocal(); alert('API key saved locally.'); }); $('#btn-load')&&$('#btn-load').addEventListener('click',()=>{ state.tbaKey=$('#tbaKey').value.trim(); saveLocal(); loadEventData(); }); $('#btn-run-models')&&$('#btn-run-models').addEventListener('click',()=>{ state.kFactor=parseFloat($('#eloK').value||'24'); state.blend=parseFloat($('#blend').value||'0.5'); computeElo(); runPredictions(); renderAll(); }); $('#btn-set-home')&&$('#btn-set-home').addEventListener('click',()=>{ state.homeTeam='frc'+($('#homeTeam').value.trim()||'245'); $('#coachTeam').textContent=fmtTeam(state.homeTeam); saveLocal(); renderAll(); }); $('#btn-refresh-coach')&&$('#btn-refresh-coach').addEventListener('click',()=> renderCoachView()); $('#btn-build-strategy')&&$('#btn-build-strategy').addEventListener('click',()=> buildStrategy()); $('#btn-rebuilt-lookup')&&$('#btn-rebuilt-lookup').addEventListener('click',()=> renderRebuiltSummary()); const el=document.getElementById('scoutFile'); const up=document.getElementById('btn-upload-scout'); up&&up.addEventListener('click',()=>{ if(!el.files||!el.files.length){ alert('Choose a CSV file first.'); return;} const file=el.files[0]; const reader=new FileReader(); reader.onload=()=>{ try{ const rows=parseCSV(reader.result); ingestScouting(rows); alert('Scouting data imported: '+rows.length+' rows.'); }catch(e){ console.error(e); alert('Failed to parse CSV.'); } }; reader.readAsText(file); }); const clr=document.getElementById('btn-clear-scout'); clr&&clr.addEventListener('click',()=>{ state.scouting={rows:[],byMatch:new Map(),byTeam:new Map()}; localStorage.removeItem('frc_scout_summary'); renderScouting(); runPredictions(); renderCoachView(); }); $$('.tab').forEach(btn=> btn.addEventListener('click',()=>{ $$('.tab').forEach(b=> b.classList.remove('active')); btn.classList.add('active'); const tab=btn.dataset.tab; $$('.tab-content').forEach(s=> s.classList.remove('active')); const panel=document.getElementById('tab-'+tab); if(panel) panel.classList.add('active'); })); $('#btn-clear-cache')&&$('#btn-clear-cache').addEventListener('click',()=>{ clearCache(); alert('Cache cleared.'); }); });
